version: '3'

services:
  recommender_db:
    image: postgres:12.2
    restart: always
    env_file:
      - ./.env
    ports:
      - "6432:5432"
    networks:
      - smart-theater
    volumes:
      - ./volumes/postgresql/pg-data:/var/lib/postgresql/data

  recommender_grpc:
    image: shumoff/smart-theater-recommender:latest
    command: python run.py serve
    restart: always
    env_file:
      - ./.env
    ports:
      - "50051:50051"
    networks:
      - smart-theater
    depends_on:
      - recommender_db
    volumes:
      - ./volumes/log:/var/log

networks:
  smart-theater:
    name: smart-theater
