version: '3'

services:
  db:
    image: postgres:12.2
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgresql/pg-data:/var/lib/postgresql/data

  web:
    build: .
    command: python run.py serve
    restart: always
    env_file:
      - ./.env
    ports:
      - "50051:50051"
    depends_on:
      - db
    volumes:
      - .:/code
      - ./volumes/log:/var/log
