# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recommender.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='recommender.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11recommender.proto\"=\n\x15RecommendationRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x13\n\x0bmax_results\x18\x02 \x01(\x05\"0\n\x13MovieRecommendation\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\"G\n\x16RecommendationResponse\x12-\n\x0frecommendations\x18\x01 \x03(\x0b\x32\x14.MovieRecommendation2K\n\x0bRecommender\x12<\n\tRecommend\x12\x16.RecommendationRequest\x1a\x17.RecommendationResponseb\x06proto3'
)




_RECOMMENDATIONREQUEST = _descriptor.Descriptor(
  name='RecommendationRequest',
  full_name='RecommendationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='RecommendationRequest.user_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_results', full_name='RecommendationRequest.max_results', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=82,
)


_MOVIERECOMMENDATION = _descriptor.Descriptor(
  name='MovieRecommendation',
  full_name='MovieRecommendation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='MovieRecommendation.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='title', full_name='MovieRecommendation.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=132,
)


_RECOMMENDATIONRESPONSE = _descriptor.Descriptor(
  name='RecommendationResponse',
  full_name='RecommendationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='recommendations', full_name='RecommendationResponse.recommendations', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=205,
)

_RECOMMENDATIONRESPONSE.fields_by_name['recommendations'].message_type = _MOVIERECOMMENDATION
DESCRIPTOR.message_types_by_name['RecommendationRequest'] = _RECOMMENDATIONREQUEST
DESCRIPTOR.message_types_by_name['MovieRecommendation'] = _MOVIERECOMMENDATION
DESCRIPTOR.message_types_by_name['RecommendationResponse'] = _RECOMMENDATIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RecommendationRequest = _reflection.GeneratedProtocolMessageType('RecommendationRequest', (_message.Message,), {
  'DESCRIPTOR' : _RECOMMENDATIONREQUEST,
  '__module__' : 'recommender_pb2'
  # @@protoc_insertion_point(class_scope:RecommendationRequest)
  })
_sym_db.RegisterMessage(RecommendationRequest)

MovieRecommendation = _reflection.GeneratedProtocolMessageType('MovieRecommendation', (_message.Message,), {
  'DESCRIPTOR' : _MOVIERECOMMENDATION,
  '__module__' : 'recommender_pb2'
  # @@protoc_insertion_point(class_scope:MovieRecommendation)
  })
_sym_db.RegisterMessage(MovieRecommendation)

RecommendationResponse = _reflection.GeneratedProtocolMessageType('RecommendationResponse', (_message.Message,), {
  'DESCRIPTOR' : _RECOMMENDATIONRESPONSE,
  '__module__' : 'recommender_pb2'
  # @@protoc_insertion_point(class_scope:RecommendationResponse)
  })
_sym_db.RegisterMessage(RecommendationResponse)



_RECOMMENDER = _descriptor.ServiceDescriptor(
  name='Recommender',
  full_name='Recommender',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=207,
  serialized_end=282,
  methods=[
  _descriptor.MethodDescriptor(
    name='Recommend',
    full_name='Recommender.Recommend',
    index=0,
    containing_service=None,
    input_type=_RECOMMENDATIONREQUEST,
    output_type=_RECOMMENDATIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RECOMMENDER)

DESCRIPTOR.services_by_name['Recommender'] = _RECOMMENDER

# @@protoc_insertion_point(module_scope)
